version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: echo "A first hello worldaaaajaaaaaaaaahjhj"
      - run: apt-get update
      - run: apt-get -y install rabbitmq-server redis-server redis-tools python python-dev python-minimal libffi-dev libssl-dev python-twisted wget
      - run: wget -qO - http://bit.ly/jasmin-deb-repo | bash
      - run: apt-get -y install python-jasmin
      - run: rm -f /etc/jasmin/store/*
      - run: cp store/* /etc/jasmin/store/
      - run: cat /etc/jasmin/store/jcli-prod.smppccs
workflows:
  version: 2
  build_and_configure:
    jobs:
      - build
